#ddev-gitpod-generated
version: "3.6"
services:
  web:
    environment:
      - DRUSH_OPTIONS_URI=https://8080-chocolate-mink-uf3jvyen.ws-us18.gitpod.io
    extra_hosts:
    - "host.docker.internal:10.64.16.142"
